apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2020-01-27T03:46:24Z"
  generation: 1
  name: submarineclusters.submarine.apache.org
  resourceVersion: "172901"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/submarineclusters.submarine.apache.org
  uid: 96ee5ef5-40b7-11ea-8e11-0242ac110002
spec:
  additionalPrinterColumns:
    - JSONPath: .metadata.creationTimestamp
      description: |-
        CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

        Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
      name: Age
      type: date
  group: submarine.apache.org
  names:
    kind: SubmarineCluster
    listKind: SubmarineClusterList
    plural: submarineclusters
    shortNames:
      - submarine
    singular: submarinecluster
  scope: Namespaced
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
status:
  acceptedNames:
    kind: SubmarineCluster
    listKind: SubmarineClusterList
    plural: submarineclusters
    shortNames:
      - submarine
    singular: submarinecluster
  conditions:
    - lastTransitionTime: "2020-01-27T03:46:24Z"
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: null
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
  storedVersions:
    - v1alpha1
