name: Deploy submarine docker images

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    strategy:
      fail-fast: true
    env:
      SUBMARINE_VERSION: 0.6.0-SNAPSHOT 
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with: 
          repository: apache/submarine
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Submarine repo
        run: mvn clean install -DskipTests
      
      - name: Build submarine server
        run: ./dev-support/docker-images/submarine/build.sh
      - name: Push submarine-server docker image
        run: docker push apache/submarine:server-$SUBMARINE_VERSION
      
      - name: Build submarine database
        run: ./dev-support/docker-images/database/build.sh
      - name: Push submarine-database docker image
        run: docker push apache/submarine:database-$SUBMARINE_VERSION
      
      - name: Build submarine jupyter
        run: ./dev-support/docker-images/jupyter/build.sh
      - name: Push submarine-jupyter docker image
        run: docker push apache/submarine:jupyter-notebook-$SUBMARINE_VERSION
      
      - name: Build submarine operator
        run: ./dev-support/docker-images/operator/build.sh
      - name: Push submarine-operator docker image
        run: docker push apache/submarine:operator-$SUBMARINE_VERSION
